src/transifex/transifex/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import redirect_to
import authority

from userena import views as userena_views

from txcommon.forms import EditProfileForm, CustomContactForm
from txcommon.feeds import UserFeed
from txcommon.views import profile_edit as txcommon_profile_edit

# Overriding 500 error handler
handler500 = 'views.server_error'

admin.autodiscover()
authority.autodiscover()

panel_url = getattr(settings,'DJANGO_ADMIN_PANEL_URL', 'admin')

urlpatterns = patterns('',)

if settings.ENABLE_ADDONS:
    urlpatterns += patterns('', (r'', include('django_addons.urls')))

PROJECTS_URL = '^projects/'

js_info_dict = {
    'domain' : 'djangojs',
}

urlpatterns += patterns('',
    url(r'^$', 'txcommon.views.index', name='transifex.home'),
    url(PROJECTS_URL, include('projects.urls')),
    url(r'^search/$', 'txcommon.views.search', name='search'),
    url(r'^%s/doc/' % panel_url, include('django.contrib.admindocs.urls')),
    url(r'^%s/' % panel_url, include(admin.site.urls)),
    url(r'^languages/', include('languages.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ajax/', include('ajax_select.urls')),
    url(r'^ajax/', include('resources.urls.ajax')),
    url(r'^api/', include('api.urls')),
    url(r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),
    url(r'^contact/$', 'contact_form.views.contact_form',
        {'form_class': CustomContactForm}, name='contact_form'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict,
        name='jsi18n'),
)

if settings.ENABLE_CONTACT_FORM:
    urlpatterns += patterns('',
        url(r'^contact/', include('contact_form.urls'), name='contact'),
    )

urlpatterns += patterns('',
        url(r'^accounts/profile/(?P<username>.+)/feed/$', UserFeed(), name='user_feed')
)

if settings.ENABLE_SIMPLEAUTH:
    urlpatterns += patterns('',
        url(r'^accounts/', include('simpleauth.urls')),)
else:
    urlpatterns += patterns('',
        # Custom EditProfileForm
        url(regex   =   r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
            view    =   login_required(txcommon_profile_edit),
            kwargs  =   {'edit_profile_form': EditProfileForm},
            name    =   'userena_profile_edit'),

        url(regex   =   r'^accounts/(?P<username>[\.\w]+)/password/$',
            view    =   'txcommon.views.password_change_custom',
            name    =   'password_change_redirect'),

        url(regex   =   r'^accounts/(?P<username>[\.\w]+)/email/$',
            view    =   login_required(userena_views.email_change),
            name    =   'userena_email_change'),

        url(regex   =   r'^accounts/(?P<username>[\.\w]+)/password/$',
            view    =   login_required(userena_views.password_change),
            name    =   'userena_password_change'),

        url(regex   =   r'^accounts/(?P<username>[\.\w]+)/edit/$',
            view    =   login_required(userena_views.profile_edit),
            name    =   'userena_profile_edit'),
 
        url(regex   =   r'^accounts/',
            view    =   include('userena.urls')),

        url(regex   =   r'^accounts/profile/(?P<username>.+)/$',
            view    =   'txcommon.views.profile_public',
            name    =   'profile_public'),
    )

if settings.USE_SOCIAL_LOGIN:
    urlpatterns += patterns('',
        url(r'^accounts/', include('social_auth.urls')),
        url(r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/social/$',
            view='txcommon.views.profile_social_settings', name='profile_social_settings'),
        # Ugly, see comments in view
        url(r'^profile/social/$', 'txcommon.views.profile_social_settings_redirect',
            name='profile-social-redirect'),
    )

if settings.ENABLE_NOTICES:
    urlpatterns += patterns('',
        url(r'^notices/feed/$', 'txcommon.views.feed_for_user', name="notification_feed_for_user"),
        (r'^notices/', include('notification.urls')),
        url(r'^accounts/nudge/(?P<username>.+)/$', 'txcommon.views.user_nudge', name='user_nudge'),
    )

if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        url(r'^site_media/media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^', include('django.contrib.staticfiles.urls'))
   )

src/transifex/transifex/teams/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, get_model, permalink
from django.utils.translation import ugettext_lazy as _
from transifex.languages.models import Language
from transifex.projects.models import Project
from transifex.txcommon.log import log_model
from transifex.resources.utils import invalidate_template_cache

class TeamManager(models.Manager):

    def get_or_none(self, project, language_code):
        """
        Return a Team object or None if it doesn't exist.
        """
        if project.outsource:
            project=project.outsource
        try:
            return self.get(project__pk=project.pk,
                language__code__exact=language_code)
        except Team.DoesNotExist:
            return None

    def public(self):
        return self.filter(project__private=False)

    def private(self):
        return self.filter(project__private=True)

class Team(models.Model):
    """
    A team is a set of people that work together in pro of a project in a
    specific language.
    """
    project = models.ForeignKey(Project, verbose_name=_('Project'),
        blank=False, null=False,
        help_text=_("The project this team works on."))
    language = models.ForeignKey(Language, verbose_name=_('Language'),
        blank=False, null=False, related_name='teams',
        help_text=_("People in this team will only be able to submit "
                    "translations files related to the specific language."))
    coordinators = models.ManyToManyField(User, verbose_name=_('Coordinators'),
        related_name='team_coordinators', blank=False, null=False)
    members = models.ManyToManyField(User, verbose_name=_('Members'),
        related_name='team_members', blank=True, null=True)
    reviewers = models.ManyToManyField(User, verbose_name=_('Reviewers'),
        related_name='team_reviewers', blank=True, null=True)

    mainlist = models.EmailField(_('Mainlist'), max_length=50, blank=True,
        null=True, help_text=_("The main mailing list of the team."))

    creator = models.ForeignKey(User, verbose_name=_('creator'), blank=False,
        null=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    # Managers
    objects = TeamManager()

    def __unicode__(self):
        return u'%s.%s' % (self.project.slug, self.language.code)

    def __repr__(self):
        return '<Team: %s.%s>' % (self.project.slug, self.language.code)

    @permalink
    def get_absolute_url(self):
        return ('team_detail', [self.project.slug, self.language.code])

    class Meta:
        unique_together = ("project", "language")
        verbose_name = _('team')
        verbose_name_plural = _('teams')

    @property
    def full_name(self):
        return "team.%s.%s" % (self.project.slug, self.language.code)

    def save(self, *args, **kwargs):
        """
        Do some extra processing along with the actual save to db.
        """
        super(Team, self).save(*args, **kwargs)
        Resource = get_model('resources', 'Resource')
        RLStats = get_model('resources', 'RLStats')
        res = Resource.objects.filter(Q(project=self.project) | 
            Q(project__outsource=self.project))
        for r in res:
            RLStats.objects.get_or_create(resource=r, language=self.language)
            invalidate_template_cache("project_resource_details",
                self.project.slug, r.slug)
            invalidate_template_cache("resource_details",
                self.project.slug, r.slug)

    def delete(self, *args, **kwargs):
        """
        Do some extra processing along with the actual delete to db.
        """
        Resource = get_model('resources', 'Resource')
        RLStats = get_model('resources', 'RLStats')
        res = Resource.objects.filter(project=self.project)
        for r in res:
            # FIXME: Maybe we should delete translations either way?
            rl, created = RLStats.objects.get_or_create(resource=r, language=self.language)
            if rl.translated == 0:
                rl.delete()
            invalidate_template_cache("project_resource_details",
                self.project.slug, r.slug)
            invalidate_template_cache("resource_details",
                self.project.slug, r.slug)
        super(Team, self).delete(*args, **kwargs)


log_model(Team)


class TeamRequest(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('Project'),
        blank=False, null=False,
        help_text=_("The project this team works on."))
    language = models.ForeignKey(Language, verbose_name=_('Language'),
        blank=False, null=False,
        help_text=_("People in this team will only be able to submit "
                    "translations files related to the specific language."))
    user = models.ForeignKey(User, verbose_name=_('User'),
        blank=False, null=False)

    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __unicode__(self):
        return u'%s.%s' % (self.project.slug,
            self.language.code)

    def __repr__(self):
        return '<TeamRequest: %s.%s>' % (self.project.slug,
            self.language.code)

    class Meta:
        unique_together = ("project", "language")
        verbose_name = _('team creation request')
        verbose_name_plural = _('team creation requests')

log_model(TeamRequest)


class TeamAccessRequestManager(models.Manager):

    def get_or_none(self, team, user):
        """
        Return a TeamAccessRequest object or None if it doesn't exist.
        """
        try:
            return self.get(team__pk=team.pk,
                user__pk__exact=user.pk)
        except TeamAccessRequest.DoesNotExist:
            return None

class TeamAccessRequest(models.Model):
    team = models.ForeignKey(Team, verbose_name=_('Team'),
        blank=False, null=False)
    user = models.ForeignKey(User, verbose_name=_('User'),
        blank=False, null=False)

    created = models.DateTimeField(auto_now_add=True, editable=False)

    objects = TeamAccessRequestManager()

    def __unicode__(self):
        return u'%s.%s' % (self.team, self.user)

    def __repr__(self):
        return '<TeamAccessRequest: %s.%s>' % (self.team, self.user)

    class Meta:
        unique_together = ("team", "user")
        verbose_name = _('team access request')
        verbose_name_plural = _('team access requests')

log_model(TeamAccessRequest)


# FIXME: We could avoid monkey-patches once custom managers on reverse 
# relations are supported in Django. https://code.djangoproject.com/ticket/3871
# Monkey-patching Project class from here to avoid circular dependency problems
def available_teams(self):
    """
    Return all available teams for the project. If the project outsources its
    access, then the teams of the 'parent' project will be returned. The 
    parameter `self` must be a Project instance.
    """
    return Team.objects.filter(project=self.outsource or self)

Project.available_teams = property(available_teams)

src/transifex/transifex/templates/teams/team_confirm_delete.html
{% extends "projects/project_menu.html" %}
{% load i18n %}

{% block title %}{{ block.super }} | {{ team.project.name }}{% endblock %}

{% block breadcrumb %}{{ block.super }} &raquo; {{ team.project.name }}{% endblock %}

{% block content_title %}
  <h2 class="pagetitle">{% blocktrans with team.language.name as lang_name %}Say goodbye to <em>{{ lang_name }}</em> team?{% endblocktrans %}</h2>
{% endblock %}

{% block content %}

<p>{% blocktrans with team.project.name as project_name and team.language.name as lang_name %}Are you sure you want to permanently delete the '{{ lang_name }}' team which works on {{ project_name }}?{% endblocktrans %}</p>

  <form action='' method='post'>{% csrf_token %}
    <input name="team_delete" type="submit" class="i16 submit buttonized" value="{% trans "Yes, I'm sure!" %}" />
  </form>

{% endblock %}

{% block content_footer %}

{% endblock %}

src/transifex/transifex/templates/teams/team_form.html
{% extends "projects/project_menu.html" %}
{% load i18n %}
{% load pagination_tags %}
{% load txcommontags %}
{% load permissions %}
{% load txpermissions %}

{% block title %}{{ block.super }} | {{ project.name }}{% endblock %}

{% block breadcrumb %}{{ block.super }} &raquo; <a href="{{ project.get_absolute_url }}">{{ project.name }}</a> &raquo; {% trans "Add Team" %}{% endblock %}

{% block content_main %}
{% with team.language as language %}
{% get_permission "project_perm.submit_translations" for request.user and project as "can_submit_translations" %}
{% get_permission "project_perm.coordinate_team" for request.user and project,language as "is_coordinator" %}

<div class="obj_bigdetails">

<h2 class="name">{% blocktrans with project.name as project_name %}{{ project_name }} Translation Teams{% endblocktrans %}</h2>

<div class="project_create generic_form">

{% if perms.projects.add_team or is_coordinator %}

<form id="add_update_team" method="post" enctype="multipart/form-data" action="" class="microform submit_form">{% csrf_token %}
 <fieldset style="margin-top: 1em;">
  <legend>{% trans "Translation team details" %}</legend>
    <div class="notice">
    {% blocktrans %}Please note that notification will not be sent when coordinators or members are added or removed on this page.{% endblocktrans %}

    </div>

    <input type="hidden" name="next" value="{{ next }}"/>
    <table>
        <tbody>
        {% form_as_table_rows project_team_form %}
        </tbody>
    </table>
    <p class="submit">
        <input name="save_team" class="i16 submit buttonized" type="submit" value="{% trans "Save team" %}"/>
    </p>
 </fieldset>
</form>
{% endif %}

</div>

	{% if team %}
		{% get_permission "project_perm.maintain" for request.user and project as "is_maintainer" %}
		{% if perms.teams.delete_team or is_maintainer %}
		<h3>{% trans "Delete team from Transifex" %}</h3>
		<div>
		  <a class="i16 delete buttonized buttonized_warning" href="{% url team_delete project.slug team.language.code %}">{% trans "Delete team..." %}</a>
		</div>
		{% endif %}
	{% endif %}

</div>
{% endwith %}
{% endblock %}

src/transifex/transifex/templates/teams/team_list.html
{% extends "projects/project_menu.html" %}
{% load i18n %}
{% load txcommontags %}
{% load permissions %}
{% load txpermissions %}
{% load statistics_resources %}

{% block extra_head %}
{{ block.super }}
<script type="text/javascript">
  $(function(){
    $("form.submit_form").hide();
    $(".tipsy_enable").tipsy({'html':true, 'gravity':'s'});
   })
</script>
{% endblock %}

{% block title %}{{ block.super }} | {{ project.name }} | {% trans "Translation Teams" %}{% endblock %}

{% block breadcrumb %}{{ block.super }} &raquo; <a href="{{ project.get_absolute_url }}">{{ project.name }}</a> &raquo; {% trans "Teams" %}{% endblock %}

{% block content_main %}
{% get_permission "project_perm.maintain" for request.user and project as "is_maintainer" %}

<div class="obj_bigdetails">

<div class="project_create generic_form">

{% with project.team_set.all|dictsort:"language.name" as teams %}
{% if teams %}
<div class="list">
<h4>{% trans "Available teams:" %}</h4>
<ul>
{% for team in teams %}
    <li class="i16 team">
        <a class="name" href="{% url team_detail team.project.slug team.language.code %}">{{ team.language.name }}</a>
          <span class="details">- {% blocktrans count team.coordinators.all|length as counter %}Coordinator:{% plural %}Coordinators:{% endblocktrans %}
            {% for c in team.coordinators.all %}
              <a href="{% url profile_public c.username %}">
                <img class="border" width="16" height="16" src="{{ c.profile.get_mugshot_url }}" style="vertical-align:bottom"/>
                {{c}}
              </a> {% if not forloop.last %},{% endif %}
            {% endfor %}
          </span>
    </li>
{% endfor %}
</ul>
</div>
{% else %}
<p>{% trans "No translation team has been created yet. Why don't you start one?" %}</p>
{% endif %}

{% if perms.projects.change_team or is_maintainer %}
<div class="addteam" style="text-align: center;">
    <a class="i16 buttonized add" href="{% url team_create project.slug %}">{% trans "Create a new team" %}</a>
</div>
{% endif %}


{% with project.teamrequest_set.all|dictsort:"language.name" as teamrequests %}
{% if teamrequests %}
<div class="list">
<h4>{% trans "Requests for new teams:" %}</h4>
<ul>
{% for teamrequest in teamrequests %}
    <li class="i16 team_request">
        <span class="name notice">{{ teamrequest.language.name }}</span>
        <span class="details">- Requester: <a href="{% url profile_public teamrequest.user.username %}">{{ teamrequest.user.username }}</a></span>

        {% if is_maintainer %}
        <form class="microform" method="post" action="{% url team_request_deny teamrequest.project.slug teamrequest.language.code %}">{% csrf_token %}
            <input name="team_request_deny" class="i16 delete buttonized" type="submit" value="{% trans "Deny" %}"/>
        </form>
        <form class="microform" method="post" action="{% url team_request_approve teamrequest.project.slug teamrequest.language.code %}">{% csrf_token %}
            <input name="team_request_approve" class="i16 submit buttonized" type="submit" value="{% trans "Approve" %}"/>
        </form>
        {% endif %}

    </li>
{% endfor %}
</ul>
</div>
{% endif %}
{% endwith %}


{% if team_request_form %}
{% if request.user.is_authenticated and not is_maintainer %}
<span class="i16 add submit_button buttonized" title="{% trans "Request a new translation team for this project" %}">{% trans "Request a new team" %}</span>
<form method="post" enctype="multipart/form-data" action="{% url team_request project.slug %}" class="add-permission microform submit_form">{% csrf_token %}
  <fieldset style="margin-top: 1em;">
   <legend>Request a new translation team</legend>
    <table>
        <tbody>
        {% form_as_table_rows team_request_form %}
        </tbody>
    </table>
    <p class="submit">
        <input name="team_request" class="i16 submit buttonized" type="submit" value="{% trans "Request team" %}"/>
    </p>
   </fieldset>
</form>
{% endif %}
{% endif %}
{% endwith %}
</div>


</div>
{% endblock %}

src/transifex/transifex/templates/teams/team_off.html
{% extends "projects/project_menu.html" %}
{% load i18n %}

{% block title %}{{ block.super }} | {{ project.name }}{% endblock %}

{% block breadcrumb %}{{ block.super }} &raquo; {{ project.name }}{% endblock %}

{% block content_main %}

<div class="obj_bigdetails">

<h2 class="name">{% trans "This project is not using Translation Teams" %}</h2>

<div>
{% url team_list project.outsource.slug as outsource_url %}
{% if outsource_url %}
  {% blocktrans with project.outsource.name as outsource_project %}This project does not maintain its own teams, but has chosen to re-use the teams of project '<a href={{ outsource_url }}>{{ outsource_project }}</a>'. In order to send translations here you'll need to join a team of '{{ outsource_project }}'.{% endblocktrans %}
{% else %}
  {% blocktrans %}This project allows translation submission from <em>anyone</em>, and thus no translation teams exist.{% endblocktrans %}
{% endif %}
</div>

</div>
{% endblock %}